#!/usr/bin/env perl

use strict;
use warnings;

my @rgb_txt = do { open my $fh, "</usr/share/X11/rgb.txt" or die "/usr/share/X11/rgb.txt: $!"; <$fh> };

print "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
print "<?xml-stylesheet type=\"text/xsl\" href=\"rgb.xsl\"?>\n";
print "<rgb>\n";

for my $line (@rgb_txt) {
   next if $line =~ /^!/; # comments
   $line =~ s/^\s+//; # leading spaces

   print "   <colour>\n";
   my ($red, $green, $blue, $name) = split /\s+/, $line, 4;
   chomp $name;
   print "      <red>$red</red>\n";
   print "      <green>$green</green>\n";
   print "      <blue>$blue</blue>\n";
   print "      <name>$name</name>\n";
   my $hexred = sprintf $red < 16 ? "0%x" : "%x", $red;
   my $hexgreen = sprintf $green < 16 ? "0%x" : "%x", $green;
   my $hexblue = sprintf $blue < 16 ? "0%x" : "%x", $blue;
   my $htmlcode = "$hexred$hexgreen$hexblue";
   printf "      <htmlcode>#$htmlcode</htmlcode>\n";
   print "   </colour>\n";
}

print "</rgb>\n";
